name: '[PROD] Trigger CVE Sync'

on: workflow_dispatch

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CVE Sync
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ctrliq/cve-update-log/dispatches \
            -d "{\"event_type\": \"trigger-prod-sync\"}"